version: '2'
services:
  postgres-oyouin:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=AQGnthVu73AjBfBF
  oyouin-main:
    image: oyouin/main
    volumes:
      - /tmp/.m2:/root/.m2
    ports:
      - "3212:8080"
    depends_on:
      - postgres-oyouin
    environment:
      - airent.db.url=jdbc:postgresql://postgres-oyouin:5432/postgres
      - LOG_DIR=/logs