version: '2'

services:

  traefik:
    ports:
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web-server

  postgres:
    image: postgres:9.6
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  web-server:
    volumes:
      - ./data/photos:/photos
      - ./data/logs:/logs
    depends_on:
      - postgres
      - logstash
    labels:
      - "traefik.enable=true"
      - "traefik.backend=web"
      - "traefik.port=9000"
    environment:
      - PROXY_HOST=91.108.64.169
      - PROXY_PORT=29842
      - PROXY_USERNAME=abarie
      - PROXY_PASSWORD=bX4BP9jM


  # elk

  elasticsearch:
    environment:
      MAX_MAP_COUNT: 262144
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    environment:
      MAX_MAP_COUNT: 262144
      NODE_OPTIONS: "--max-old-space-size=950"
    depends_on:
      - elasticsearch
    labels:
      - "traefik.enable=true"
      - "traefik.backend=kibana"
      - "traefik.port=5601"
