# override file for production
version: '2'

services:

  traefik:
    image: breezy16/traefik
    volumes:
      - ./data/acme:/encrypt/acme

  web-server:
    image: breezy16/web-server
    labels:
      - "traefik.frontend.rule=Host:fatirlar.ru"
    environment:
      - IMPORT_INITIAL_DELAY=15
      - IMPORT_INTERVAL=600
      - IMPORT_ITEMS_MAX_AVITO=2500
      - IMPORT_ITEMS_MAX_TOTOOK=2500