# override file for production
version: '2'

services:

  traefik:
    volumes:
      - ./traefik.prod.toml:/etc/traefik/traefik.toml
      - ./data/acme:/encrypt/acme

  web-server:
    environment:
      - IMPORT_INITIAL_DELAY=15
      - IMPORT_INTERVAL=600
      - IMPORT_ITEMS_MAX_AVITO=2500
      - IMPORT_ITEMS_MAX_TOTOOK=2500