# override file for local development
version: '2'

services:

# for traefik expose admin port and use dev configuration file
  traefik:
    ports:
      - 8080:8080
    volumes:
       - ./traefik/traefik.toml:/etc/traefik/traefik.toml

# for postgres bind port locally to debug
  postgres:
    ports:
      - 5442:5432

# for web-server use different image and some caching volumes
  web-server:
    build:
      context: web-server
      dockerfile: Dockerfile-local
    labels:
      - "traefik.enable=true"
      - "traefik.backend=web"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:localhost"
    stdin_open: true
    volumes:
      - ./web-server:/web-server
      - ~/.m2:/root/.m2
      - ~/.coursierg:/root/.coursier
      - ~/.sbt:/root/.sbt
      - ~/.ivy2:/root/.ivy2
    environment:
      - IMPORT_INITIAL_DELAY=30
      - IMPORT_INTERVAL=1800000
      - IMPORT_ITEMS_MAX_AVITO=60
      - IMPORT_ITEMS_MAX_TOTOOK=60
