# override file for production
version: '2'

services:

  traefik:
    image: breezy16/traefik
    volumes:
      - ./data/acme:/encrypt/acme

  web-server:
    image: breezy16/web-server
    labels:
      - "traefik.frontend.rule=Host:fatirlar.ru,www.fatirlar.ru"
    environment:
      - IMPORT_INITIAL_DELAY=15
      - IMPORT_INTERVAL=600
      - IMPORT_ITEMS_MAX_AVITO=2500
      - IMPORT_ITEMS_MAX_TOTOOK=2500

  # elk
  elasticsearch:
    image: breezy16/elasticsearch

  logstash:
    image: breezy16/logstash

  kibana:
    image: breezy16/kibana
    labels:
      - "traefik.frontend.rule=Host:kibana.fatirlar.ru"
      - "traefik.frontend.auth.basic=kibana:$$apr1$$e6auNkNj$$JXGXJy5AI5Jr2GiSYtVKo/"