# override file for local development
version: '2'

services:

# for traefik expose admin port and use dev configuration file
  traefik:
    image: traefik
    ports:
      - 8080:8080
    volumes:
       - ./traefik/traefik.toml:/etc/traefik/traefik.toml

# for postgres bind port locally to debug
  postgres:
    ports:
      - 5442:5432

# for web-server use different image and some caching volumes
  web-server:
    build:
      context: web-server
      dockerfile: Dockerfile-local
    labels:
      - "traefik.frontend.rule=Host:localhost"
    stdin_open: true
    volumes:
      - ./web-server:/web-server
      - ~/.m2:/root/.m2
      - ~/.coursier:/root/.coursier
      - ~/.sbt:/root/.sbt
      - ~/.ivy2:/root/.ivy2
    environment:
      - IMPORT_INITIAL_DELAY=30
      - IMPORT_INTERVAL=1800000
      - IMPORT_ITEMS_MAX_AVITO=60
      - IMPORT_ITEMS_MAX_TOTOOK=60

  # elk
  elasticsearch:
    build: elk/elasticsearch

  logstash:
    build: elk/logstash

  kibana:
    build: elk/kibana
    labels:
      - "traefik.frontend.rule=Host:kibana.localhost"
      - "traefik.frontend.auth.basic=breezy:$$apr1$$1py8td5l$$bQf4j1R0QEnsqEDGyazFs/"
